spring.application.name=identity.service

# Server Configuration
server.port=8080
server.servlet.context-path=/identity


# Database Configuration
spring.datasource.url= ${DBMS_CONNECTION} # jdbc:mysql://localhost:3306/identity_service. DBMS_CONNECTION, DBMS_USERNAME, DBMS_PASSWORD are set in the environment variables, to know where it is search ChatGPT.  
spring.datasource.username= ${DBMS_USERNAME}
spring.datasource.password=${DBMS_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt.signer.key=bDpwTWiMcV4rjHhoRcgcJFIKzucBpMS6lCAgP06yNHf6mh3xi3FvC0pqu4ZpyLMjLygPt3MJhe6XooTLxbDJhvkXxMsoIxnvaUz9VAS91ZSeTfUIYX5wO0VHrHzrHN1G
jwt.valid-duration = 20
jwt.refreshable-duration = 60

