server:
  port: 8080
  servlet:
    context-path: /identity


spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# this file (.yml) should only be written in English as if we use Vietnamese there will be errors